/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedFluxoRouteImport } from './routes/_authenticated/fluxo'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFluxoRoute = AuthenticatedFluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/fluxo': typeof AuthenticatedFluxoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/redefinir-senha'
    | '/configuracoes'
    | '/fluxo'
    | '/inicio'
    | '/movimentacoes'
    | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/redefinir-senha'
    | '/configuracoes'
    | '/fluxo'
    | '/inicio'
    | '/movimentacoes'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/redefinir-senha'
    | '/_authenticated/configuracoes'
    | '/_authenticated/fluxo'
    | '/_authenticated/inicio'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo': {
      id: '/_authenticated/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof AuthenticatedFluxoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFluxoRoute: typeof AuthenticatedFluxoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFluxoRoute: AuthenticatedFluxoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
